id: P006914
initial_creation_type: ocr
source_metadata:
  id: bdr:W27301
  title: རེབ་གོང་གསེར་མོ་ལྗོངས་ཞེས་ཡོངས་སུ་གྲགས་པའི་ཆོས་སྲིད་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ་འདོད་འབྱུང་གཏེར་གྱི་བུམ་བཟང
  author: ''
  volumes: {}
