id: P006914
initial_creation_type: ocr
source_metadata:
  id: bdr:W27301
  title: རེབ་གོང་གསེར་མོ་ལྗོངས་ཞེས་ཡོངས་སུ་གྲགས་པའི་ཆོས་སྲིད་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ་འདོད་འབྱུང་གཏེར་གྱི་བུམ་བཟང
  author: ''
  volumes:
    dfbb8f5a24ec4f3196ab26f2391eb2b6:
      image_group_id: I4258
      title: ''
      volume_number: 1
      total_pages: 260
