id: I322B309E
legacy_id: P006914
ocr_import_info:
  bdrc_scan_id: W27301
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T15:16:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:06:58.960225+00:00'
last_modified: 2022-09-02 15:07:24.146458
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27301
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27301
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རེབ་གོང་གསེར་མོ་ལྗོངས་ཞེས་ཡོངས་སུ་གྲགས་པའི་ཆོས་སྲིད་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ་འདོད་འབྱུང་གཏེར་གྱི་བུམ་བཟང་།
  author: གླིང་རྒྱ་བ་བླ་མ་ཚེ་རིང་།
statistics:
  ocr_word_mean_confidence_index: 0.9548186289644135
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4258:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4258
      total_pages: 260
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4258.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9548186289644135
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
