id: I322B309E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:18:14+00:00'
last_modified: '2022-06-08T09:36:30.823431+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27301
  title: རེབ་གོང་གསེར་མོ་ལྗོངས་ཞེས་ཡོངས་སུ་གྲགས་པའི་ཆོས་སྲིད་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ་འདོད་འབྱུང་གཏེར་གྱི་བུམ་བཟང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    66AA:
      image_group_id: I4258
      title: ''
      total_pages: 260
      order: 1
      base_file: 66AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
